```{r}
require('R2jags')
```

```{r}
m1.mod <-"
model {
  for (i in 1:N){
    Y[i] ~ dnorm(mu, invS2)}
  mu ~ dnorm(a,1/b)
  invS2 ~ dgamma(.5,.5*r)
}
"

runMod1 = function(Y,M=1000){
  setup=list(
    "Y" = Y,
    "N" = length(Y))
  prior =list("a"=100,"b"=5^2,"r"=15^2)
  pars = c("mu","invS2")
  out=jags(data=c(setup,prior), 
           parameters=pars, 
           model.file = textConnection(m1.mod), 
           n.chains=1,n.iter=M,n.burnin=M/10,n.thin=1)
  return(out)}
```

```{r}
out=runMod1(c(92,115,100,98))
```

```{r}
mu=out$BUGSoutput$sims.list$mu
s2=1/out$BUGSoutput$sims.list$invS2
hist(mu)
hist(sqrt(s2))
```

```{r}
m2.mod <-"

model {
  eta ~ dnorm(a,1/b)
  invDel ~dgamma(.5,.5*r2)
  invS2 ~ dgamma(.5,.5*r1)
  for (i in 1:I){
    mu[i] ~ dnorm(eta,invDel)}
  for (n in 1:N){
    Y[n] ~ dnorm(mu[sub[n]],invS2)}  
}
"

runM2=function(dat,M=1000){
  setup=list(
    "Y" = dat$y,
    "I" = length(unique(dat$sub)),
    "N" = length(dat$y),
    "sub" = dat$sub)
  prior =list("a"=400,
              "b"=600^2,
              "r1"=200^2,
              "r2"=50^2)
  pars = c("mu","invS2","eta","invDel")
  out=jags(data=c(setup,prior), 
           parameters=pars, 
           model.file = textConnection(m2.mod), 
           n.chains=1,n.iter=M,n.burnin=M/10,n.thin=1)
  return(out)}
```

```{r}
dat=read.table('hier1.dat',head=T)
out=runM2(dat)
```