```{r}
library(rstan)
rstan_options(auto_write = TRUE)

dat=readRDS('datRT.RDS')
rt=dat$rt
sub=dat$sub
cond=dat$cond
x=dat$cond-3/2
```

```{r}
m1C <- "

data {          
  int<lower=0> n; 
  vector[n] y;
}

parameters {
  real mu;
  real<lower=0> sigma2;
}

transformed parameters {
  real<lower=0> sigma;
  sigma = sqrt(sigma2);   
}

model {
  mu ~ normal(0,1);
  sigma2 ~ inv_gamma(.5,.5);
  y ~ normal(mu,sigma);
}"
```


```{r}
y=rt[sub==1 & cond==2]
n=length(y)
x=x[dat$sub==1]
data <- list(y=y, n=n)
m1 <- stan_model(model_code = m1C)
samples <- sampling(m1, data=data, iter=1000, chains=1)
mu <- extract(samples)$mu
sigma <- extract(samples)$sigma
plot(mu)
```



```{r}
m2C <- "

data {          
  int<lower=0> n;
  vector[n] x;
  vector[n] y;
}

parameters {
  real mu;
  real alpha;
  real<lower=0> sigma2;
}

transformed parameters {
  real<lower=0> sigma;
  vector[n] center;
  sigma = sqrt(sigma2);
  for (i in 1:n){
    center[i] = mu+x[i]*alpha;}   
}

model {
  mu ~ normal(0,1);
  alpha ~ normal(0,1);
  sigma2 ~ inv_gamma(.5,.5);
  y ~ normal(center,sigma);
}"
```


```{r}
y=rt[sub==1]
n=length(y)
x=x[sub==1]
data <- list(y=y, n=n, x=x)
m2 <- stan_model(model_code = m2C)
samples <- sampling(m2, data=data, iter=1000, chains=1)
mu <- extract(samples)$mu
alpha <-extract(samples)$alpha
sigma <- extract(samples)$sigma
plot(mu)
```
```{r}
m3C <- "

data {          
  int<lower=0> n;
  int<lower=0> I;
  vector[n] x;
  vector[n] y;
  int sub[n];
}

parameters {
  vector[I] mu;
  vector[I] alpha;
  real<lower=0> sigma2;
}

transformed parameters {
  real<lower=0> sigma;
  vector[n] center;
  sigma = sqrt(sigma2);
  for (i in 1:n){
    center[i] = mu[sub[i]]+x[i]*alpha[sub[i]];}   
}

model {
  mu ~ normal(0,1);
  alpha ~ normal(0,1);
  sigma2 ~ inv_gamma(.5,.5);
  y ~ normal(center,sigma);
}"
```


```{r}
y=dat$rt
n=length(y)
I=length(unique(sub))
x=dat$cond-3/2
data <- list(y=y, n=n, x=x, sub=sub, I=I)
m3 <- stan_model(model_code = m3C)
samples <- sampling(m3, data=data, iter=2000, chains=1)
mu <- extract(samples)$mu
plot(apply(mu,2,mean))
alpha <-extract(samples)$alpha
sigma <- extract(samples)$sigma
```



```{r}
m4C <- "

data {          
  int<lower=0> n;
  int<lower=0> I;
  vector[n] x;
  vector[n] y;
  int sub[n];
}

parameters {
  vector[I] mu;
  vector[I] alpha;
  real<lower=0> sigma2;
  real<lower=0> delta2M;
  real<lower=0> delta2A;
  real nuMu;
  real nuAlpha;
}

transformed parameters {
  real<lower=0> sigma;
  real<lower=0> deltaM;
  real<lower=0> deltaA;
  vector[n] center;
  deltaM = sqrt(delta2M);
  deltaA = sqrt(delta2A);
  sigma = sqrt(sigma2);
  for (i in 1:n){
    center[i] = mu[sub[i]]+x[i]*alpha[sub[i]];}   
}

model {
  mu ~ normal(nuMu,deltaM);
  alpha ~ normal (nuAlpha,deltaA);
  nuAlpha~ normal(0,1);
  nuMu~ normal(0,1);
  delta2M ~ inv_gamma(.5,.5); 
  delta2A ~ inv_gamma(.5,.5);
  sigma2 ~ inv_gamma(.5,.5);
  y ~ normal(center,sigma);
}"
```


```{r}
y=log(dat$rt)
n=length(y)
I=length(unique(sub))
x=dat$cond-3/2
data <- list(y=y, n=n, x=x, sub=sub, I=I)
m4 <- stan_model(model_code = m4C)
samples <- sampling(m4, data=data, iter=2000, chains=1)
mu <- extract(samples)$mu
plot(apply(mu,2,mean))
alpha <-extract(samples)$alpha
sigma <- extract(samples)$sigma
```




```{r}
m5C <- "

data {          
  int<lower=0> n;
  int<lower=0> I;
  vector[n] x;
  vector[n] y;
  int sub[n];
}

parameters {
  vector[I] mu;
  vector[I] alpha;
  real<lower=0> sigma2;
  real<lower=0> delta2M;
  real<lower=0> delta2A;
  real nuMu;
  real nuAlpha;
}

transformed parameters {
  real<lower=0> sigma;
  real<lower=0> deltaM;
  real<lower=0> deltaA;
  vector[n] center;
  deltaM = sqrt(delta2M);
  deltaA = sqrt(delta2A);
  sigma = sqrt(sigma2);
  for (i in 1:n){
    center[i] = mu[sub[i]]+x[i]*alpha[sub[i]];}   
}

model {
  mu ~ normal(nuMu,deltaM);
  alpha ~ normal (nuAlpha,deltaA);
  nuAlpha~ normal(0,1);
  nuMu~ normal(0,1);
  delta2M ~ inv_gamma(.5,.5); 
  delta2A ~ inv_gamma(.5,.5);
  sigma2 ~ inv_gamma(.5,.5);
  y ~ lognormal(center,sigma);
}"
```


```{r}
y=dat$rt
n=length(y)
I=length(unique(sub))
x=dat$cond-3/2
data <- list(y=y, n=n, x=x, sub=sub, I=I)
m5 <- stan_model(model_code = m5C)
samples <- sampling(m5, data=data, iter=2000, chains=1)
mu <- extract(samples)$mu
plot(apply(mu,2,mean))
alpha <-extract(samples)$alpha
sigma <- extract(samples)$sigma
```